version: 2.1

jobs:
  test-python:
    docker:
      - image: cimg/python:3.11
    environment:
      PYTHONPATH: .
    steps:
      - checkout
      - run:
          name: Actualizar pip e instalar pytest
          command: |
            python -m pip install --upgrade pip
            pip install pytest
      - run:
          name: Ejecutar tests con pytest
          command: pytest --junitxml=junit.xml
      - store_test_results:
          path: junit.xml

workflows:
  build-and-test:
    jobs:
      - test-python
