version: 2.1

jobs:
  test-python:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Instalar pytest
          command: |
            python -m pip install --upgrade pip
            pip install pytest
      - run:
          name: Ejecutar tests
          command: pytest --junitxml=junit.xml || (exit 1)
      - store_test_results:
          path: junit.xml

workflows:
  build-and-test:
    jobs:
      - test-python
