version: 2.1

jobs:
  setup:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Instalar pytest
          command: |
            python -m pip install --upgrade pip
            pip install pytest
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: cimg/python:3.11
    environment:
      PYTHONPATH: .
    parallelism: 2
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Ejecutar tests en paralelo
          command: |
            circleci tests split --split-by=timings tests | xargs pytest --junitxml=test-results/junit-${CIRCLE_NODE_INDEX}.xml
      - store_test_results:
          path: test-results

  notify:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Notificación simple (mostrar estado)
          when: always
          command: |
            echo "Pipeline finalizó con estado: ${CIRCLE_JOB} en la rama ${CIRCLE_BRANCH}"

workflows:
  version: 2
  build-and-test:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - notify:
          requires:
            - test
