# .github/workflows/security_scan.yml
name: Security Scan with Bandit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bandit_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Correct your requirements.txt filename to 'requirements.txt'
        # pip install -r requirements.txt # Uncomment if Bandit is in your requirements.txt
        pip install bandit # Ensure Bandit is installed
        pip install jq # Install jq for JSON parsing

    - name: Run Bandit Scan
      id: bandit_scan
      run: |
        cd app
        bandit -r . -f json -o ../bandit-results.json || true
      continue-on-error: true # Allow the workflow to continue even if Bandit finds issues for reporting

    - name: Check Bandit Results and Fail Build
      run: |
        if [ -f bandit-results.json ]; then
          HIGH_ISSUES=$(jq '._totals.SEVERITY.HIGH' bandit-results.json)
          MEDIUM_ISSUES=$(jq '._totals.SEVERITY.MEDIUM' bandit-results.json)

          echo "Bandit found High issues: $HIGH_ISSUES"
          echo "Bandit found Medium issues: $MEDIUM_ISSUES"

          if [ "$HIGH_ISSUES" -gt 0 ] || [ "$MEDIUM_ISSUES" -gt 0 ]; then
            echo "::error file=bandit-results.json::Bandit found security issues (High: $HIGH_ISSUES, Medium: $MEDIUM_ISSUES). Please review and fix."
            exit 1 # Fail the workflow
          else
            echo "No High or Medium Bandit issues found. Good job!"
          fi
        else
          echo "Bandit results file (bandit-results.json) not found. Skipping issue check."
          exit 1 # Fail if the report wasn't generated
        fi
      shell: bash # Explicitly use bash for the script

    - name: Upload Bandit Report
      uses: actions/upload-artifact@v4
      with:
        name: bandit-report
        path: bandit-results.json
        if-no-files-found: ignore